dbjorge/jorbs-spire-mod

README.md
pom.xml

With these changes pom.xml does not have to be edited if the paths are not the same as in the example, and thus will not appear as a local change or even be committed by accident.

Extracted local paths to settings.xml

---

README.md

For anyone who has a bad fork, they can fix it with these two commands:
`git remote set-url my_fork https://github.com/your_username/jorbs-spire-mod.git`
`git remote set-url --push my_fork https://github.com/your_username/jorbs-spire-mod.git`

Add two links and fix fork URL

---

src/main/java/stsjorbsmod/cards/wanderer/Withdraw.java

addresses #85 where Withdraw is not exhausting. This makes Withdraw exhaust on use.

make withdraw exhaust

---

src/main/java/stsjorbsmod/actions/RemovePowersMatchingPredicateAction.java
src/main/java/stsjorbsmod/cards/wanderer/Amnesia.java
src/main/java/stsjorbsmod/patches/EnumsPatch.java
src/main/java/stsjorbsmod/powers/SnappedPower.java
src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Card-Strings.json

Artifacts doesn't block SnappedPower from applying anymore
Amnesia doesn't cleanse SnappedPower anymore
Amnesia is now an unplayable curse. card effects occur at the end of turn.
Amnesia text order to betters matches order of card actions

SnappedPower should be unblockable uncleansable

---

src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Card-Strings.json
src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Keyword-Strings.json

This gives it an explanation on Entangle, because it's not recognized as a keyword from the main game.
Cleanup tense and try explaining the "maintain" concept by stating instead that the effect lasts until the cause is forgotten.

Add Slow as a keyword.

---

src/main/java/stsjorbsmod/JorbsMod.java
src/main/java/stsjorbsmod/cards/CardSaveData.java
src/main/java/stsjorbsmod/cards/CustomJorbsModCard.java
src/main/java/stsjorbsmod/cards/JorbsCardPersistentData.java
src/main/java/stsjorbsmod/memories/WrathMemory.java
src/main/java/stsjorbsmod/patches/AbstractCardMakeStatEquivalentCopyPatch.java
src/main/java/stsjorbsmod/patches/WrathField.java

Cards save their ID, number of upgrades, and their misc field by
default. To save how Wrath modifies a card's base damage, we
implement the CustomSavable interface on all of our cards and
introduce a new class to track persistent changes. Currently the only
value is how much Wrath modifies a card. Persistent changes are
re-applied to cards upon loading.
REVIEW: The addition of the save class seems like extra work for what's just one field. When I originally had it implemented as an Integer, I was seeing odd behavior, where the value seemed to be lost over time. I was wondering if something about a common class like Integer caused problems with deserializing the JSON in the mainline code. I never root caused the problem, but after changing to a unique class I haven't been able to repro the …

Persist Wrath modifiers across play sessions

---

src/main/java/stsjorbsmod/cards/CardSaveData.java
src/main/java/stsjorbsmod/memories/WrathMemory.java

Ritual Dagger is the only main game attack that tracks damage
differently. We handle it as a special case, rather than trying to
be general for whatever other mods might do.
Resolves #109.
I really should just sleep and push in the morning, but I want that feeling of accomplishment. No matter that it takes twice as long at this time of day to check the work.

Fix Wrath to stack with Ritual Dagger

---

src/main/resources/stsjorbsmodResources/localization/README.md
src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Keyword-Strings.json
src/main/resources/stsjorbsmodResources/localization/fra/JorbsMod-Keyword-Strings.json

Add a README with directions and suggestions for how to add new
strings to the localization files. Rearrange the keyword strings to
follow the guidance, as an example both for the guidance and its
effect on file structure.
NOTE: I don't think this is high priority. I was in the area, and I wanted to get a feel for whether this sort of guidance will be useful. If so, then some groundwork is laid.
NOTE: One oddity in the review is that FRA doesn't yet have localization for the keyword Slow. That absence leads to some difference in the diffs for ENG and FRA.

Provide directions for strings

---

src/main/java/stsjorbsmod/cards/wanderer/AnimateObjects.java
src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Card-Strings.json

From the spreadsheet for current intended card effects, remove the
upgrade ability to copy itself. Change the damage to hit once per
eligible card found. Modify description to match new behavior.
Resolves #73.

Update Animate Objects

---

src/main/java/stsjorbsmod/cards/wanderer/ArcaneForm.java
src/main/java/stsjorbsmod/cards/wanderer/CorpseExplosion_Wanderer.java
src/main/java/stsjorbsmod/cards/wanderer/Determination.java
src/main/java/stsjorbsmod/cards/wanderer/Feast.java
src/main/java/stsjorbsmod/cards/wanderer/LocateObject.java
src/main/java/stsjorbsmod/cards/wanderer/Mending.java
src/main/java/stsjorbsmod/cards/wanderer/SmithingStrike.java
src/main/java/stsjorbsmod/characters/Wanderer.java
src/main/java/stsjorbsmod/patches/FilterRandomCardGenerationPatch.java
src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Card-Strings.json

A number of random card generation methods eliminate cards with
healing effects from the eligible set. We honor the letter and the
spirit of that filtering by tagging our direct healing cards and,
additionally, eliminating cards with a new tag indicating any other
persistent positive effects from being generated as well.
Future cards must be careful to use these tags in order to
indicate when they are not eligible to be generated as a random card.
Resolves #70.
NOTE: I took two stylistic compressions, and I'd like to be sure they seem right to other eyes.
* Patch all of the relevant functions in one file, using inner static classes.
* Use a unified locator for all patches. If a second locator had been needed, I would have given it a more specific name at that point.
NOTE: The colorless …

Fix card interaction with Nilry's Codex

---

src/main/java/stsjorbsmod/JorbsMod.java
src/main/java/stsjorbsmod/patches/LegendaryPatch.java

Resolves #131 and #151.
Fix the Duplicator event. Now the player can't select a Legendary card to copy.
Fix the Fountain of Curse Removal event from happening if the player only has Legendary curses.
Log if we ever remove or transform a Legendary card that's in the master deck.
Support the Draft and SealedDeck mods. Comment our weirder interactions with other mods.
I think there are actual bugs in the main game for the Living Wall and Designer events. They check a condition different than what they use immediately afterwards places that are key to causing trouble for us. I don't plan to investigate how to file a bug with them, though.

Finish support for Legendary cards

---

src/main/java/stsjorbsmod/memories/LustMemory.java

Gif is using un-updated scorching ray so it hits block for one. Still applies 2 Lust burning.

Lust applies on-hit, regardless of hitting block, similar to thorns.

---

src/main/java/stsjorbsmod/cards/wanderer/Determination.java
src/main/java/stsjorbsmod/cards/wanderer/Prepare.java
src/main/java/stsjorbsmod/memories/KindnessMemory.java
src/main/java/stsjorbsmod/powers/BurningPower.java
src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Card-Strings.json

Determination exhausts
Hold Monster str down ordering (now kindness's str down (if not remembered or clarified) then hold monster's str down)
Patron's keywords
Burning renders amount of damage after hitting block
Prepare blocks for exactly coil amount before dex and frail modifiers

20191208 changes

---

src/main/java/stsjorbsmod/actions/SnapAction.java
src/main/java/stsjorbsmod/util/CombatUtils.java

This should work around the issue where `AbstractMonster::areMonstersBasicallyDead` returns false if minions are still alive.
Other options include to patch `AbstractMonster::areMonstersBasicallyDead` to include minion checks, patch `DamageAction::update` to check minions, create a new DamageAction with a minion check, or Add an action for PurgeMind that removes SnapAction if only minions are left alive.
addresses #269

only snap when the combat is still ongoing

---

src/main/java/stsjorbsmod/patches/RenderBurningBlockPatch.java

Burning icon was shown any time a creature had block. Added check to RenderBurningBlockPatch that checks if creature has BurningPower.

Bugfix for #243: burning block icon shown even if owner is not burning

---

src/main/java/stsjorbsmod/actions/ConsumeCardAction.java

- only enters the rarity switch statement if card is not of CardType == Status

Bugfix #322 - Consuming a status gives +3 maxHP instead of nothing

---

src/main/java/stsjorbsmod/patches/BurningPatch.java
src/main/java/stsjorbsmod/powers/BurningPower.java
src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Keyword-Strings.json

Technically at the very end of the player's turn, just before EnemyTurnEffect gets added.
This purposefully renames the file to be a bit more generic.
addresses #321

Burning damage before block drop

---

src/main/java/stsjorbsmod/cards/cull/SpiritShield_Cull.java
src/main/java/stsjorbsmod/cards/cull/SplinterSoul.java
src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Card-Strings.json

- Splinter Soul ignores all Legendary cards in draw pile when finding a Consume target
- Spirit Shield now has Legendary tag

Implements two Cull changes regarding Legendary cards

---

src/main/java/stsjorbsmod/JorbsMod.java
src/main/java/stsjorbsmod/potions/GhostPoisonPotion.java
src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Potion-Strings.json

Gain 1 manifest for each enemy in combat, then win the combat if non-elite/non-boss.
- ends combat using m.die() on all monsters notDeadOrEscaping.

Implements Cull potion Ghost Poison

---

src/main/java/stsjorbsmod/patches/MemoryHooksPatch.java

End of turn memory effects now occur first. This makes Chastity block burns and that curse. I can't think of any particular scenario where this as any unintended side effects.

end of turn memory effects occur before relics, powers, burns, etc.

---

src/main/java/stsjorbsmod/cards/wanderer/materialcomponents/SnakeOil.java
src/main/java/stsjorbsmod/powers/CoilPower.java
src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Card-Strings.json
src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Keyword-Strings.json
src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Power-Strings.json

Snake oil remembers patience
Snake oil does not add 4 coil
Snake oil damage does not include playing itself
Coil does not trigger when remember patience
addresses #350 and #352

Snake oil + Coil

---

src/main/java/stsjorbsmod/potions/DimensionDoorPotion.java

Something in `FruitJuice` base class is overriding the name. This should just force the correct name.

it's not fruit juice

---

src/main/java/stsjorbsmod/actions/TimeEddyAction.java
src/main/java/stsjorbsmod/cards/wanderer/materialcomponents/TimeEddy.java

`TImeEddyAction` bugged me. renamed it.
`TimeEddyAction` adds itself at the end of `TimeEddyAction::update`. Assumes actions with bad interactions won't add other actions before `TimeEddyAction` goes again. 
https://youtu.be/F6tdXINTcCs
Addresses #334 end of turn dex down

rename + add TimeEddyAction in TimeEddyAction

---

src/main/java/stsjorbsmod/powers/StrangePendantPower.java

addresses #401 
it's not exactly directly addressing it, but the interaction between the two are fine, just a matter of it being non-intuitive when the reset occurs

Strange Pendant resets at the start of turn now

---

src/main/java/stsjorbsmod/patches/BottledMemoryPatch.java
src/main/java/stsjorbsmod/patches/BottledRelic_onEquipPatch.java
src/main/java/stsjorbsmod/patches/EntombedPatch.java
src/main/java/stsjorbsmod/patches/LegendaryPatch.java
src/main/java/stsjorbsmod/relics/BottledMemoryRelic.java
src/main/java/stsjorbsmod/util/CardUtils.java

- Fixes Bottled Memory being able to select entombed cards... whoops
- Fixes occasionally being able to bottle Entombed cards with base game bottle relics
- Merges Legendary, Entombed, and BottledMemory patches into a single `BottleRelics_onEquipPatch`
- Refactors bottleability into a single method

Bottle relics onEquip

---

src/main/java/stsjorbsmod/powers/ForbiddenGrimoireDelayedExhumePower.java

Addresses an issue where Will would entomb Grimoire if Will was the card that caused Grimoire to be exhumed.
This moves the grimoire's delayed exhume timing to after the card is played and adds actions to the actionmanager.

Grimoire exhume after will occurs

---

src/main/java/stsjorbsmod/actions/TimeEddyAction.java
src/main/java/stsjorbsmod/memories/AbstractMemory.java
src/main/java/stsjorbsmod/memories/ChastityMemory.java
src/main/java/stsjorbsmod/memories/DiligenceMemory.java
src/main/java/stsjorbsmod/patches/MemoryHooksPatch.java

- Brought back the old memory end turn hook for Diligence to use
- Renamed memory end turn hook to `atEndOfTurnPreEndTurnCards` for Chastity to use
- Time Eddy triggers both end turn memory hooks

Diligence uses the old hook, Chastity uses a newer hook

---

src/main/java/stsjorbsmod/cards/wanderer/BookOfTongues.java
src/main/java/stsjorbsmod/cards/wanderer/BurningFlask.java
src/main/java/stsjorbsmod/cards/wanderer/ChatteringStrike.java
src/main/java/stsjorbsmod/cards/wanderer/DeathThroes.java
src/main/java/stsjorbsmod/cards/wanderer/FlameWard.java
src/main/java/stsjorbsmod/cards/wanderer/FreshAdventure.java
src/main/java/stsjorbsmod/cards/wanderer/GatherPower.java
src/main/java/stsjorbsmod/cards/wanderer/Hibernate.java
src/main/java/stsjorbsmod/cards/wanderer/Hurt.java
src/main/java/stsjorbsmod/cards/wanderer/Materialize.java
src/main/java/stsjorbsmod/cards/wanderer/Rediscovery.java
src/main/java/stsjorbsmod/cards/wanderer/Rest.java
src/main/java/stsjorbsmod/cards/wanderer/SiphonEnergy.java
src/main/java/stsjorbsmod/cards/wanderer/TollTheDead.java
src/main/java/stsjorbsmod/cards/wanderer/Trauma.java
src/main/java/stsjorbsmod/cards/wanderer/materialcomponents/Chamomile.java
src/main/java/stsjorbsmod/cards/wanderer/materialcomponents/Quicksilver.java
src/main/java/stsjorbsmod/memories/MemoryManager.java
src/main/java/stsjorbsmod/powers/BookOfTonguesPower.java
src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Card-Strings.json
src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Power-Strings.json

- fresh adventure: -1 damage, "this card gains a wrath stack every time you snap"
- chamomile: loses vulnerable, upgrades to have vulnerable (no retain)
- quicksilver: costs 1
- burning flask: -1 burning
- chattering strike: upgrades to deal 4 damage, play this card 2 additional times
- hibernate: -1 block
- hurt: no increased damage on upgrade, upgrade adds gain clarity of current memory, still loses life per clarity
- materialize: costs 1, +1 block
- book of tongues: upgrades to innate instead of upgraded components
- flame ward: -1 burning, -1 block
- rest: -2 block
- toll the dead: -1 damage
- death throes+: no damage increase, no remember wrath, gain clarity of wrath
- gather power: -1 card draw
- trauma: shuffle into draw pile instead of put on top
- siphon energy: draw 2 cards (3 …

Balance 20200215

---

src/main/java/stsjorbsmod/memories/HumilityMemory.java

Prevent thorns from going negative when amnesia or other similar effects remove thorns rather than reduce thorns. Do this by checking if thorns is null and setting `thornsAlreadyApplied` to 0 if true.

Humility amnesia negative thorns

---

src/main/java/stsjorbsmod/powers/BanishedPower.java

Opens up banished power to allow instances of BackAttackPower to be applied.
Fixes #443

Apply BackAttackPower to Banished targets

---

src/main/java/stsjorbsmod/cards/wanderer/ArcaneForm.java
src/main/java/stsjorbsmod/cards/wanderer/Mindworm.java
src/main/java/stsjorbsmod/cards/wanderer/OldPocket.java
src/main/java/stsjorbsmod/memories/GreedMemory.java
src/main/java/stsjorbsmod/memories/HumilityMemory.java
src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Card-Strings.json
src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Keyword-Strings.json
src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Memory-Strings.json

Fixes #447 
Also includes recoloring of the text used in memories. Numbers to blue, Remember/Passive to purple

20200302 balance

---

src/main/java/stsjorbsmod/memories/AbstractMemory.java
src/main/java/stsjorbsmod/memories/SnapCounter.java
src/main/java/stsjorbsmod/twitch/SlayTheRelicsIntegration.java

- allows rendering PowerTips on stream, this integration allows rendering of custom
PowerTips unique to this mod - the memories and the snap counter
- tested live on twitch with the Wanderer, also with Defect and Ironclad playing
Arcane Form. In all cases the tips were displayed properly on stream
- rendering of the hitboxes is purposefully not conditioned on:
(!AbstractDungeon.isScreenUp || PeekButton.isPeeking)
the decision whether to respect this is left up to the SlayTheRelics mod.
Hiding the powertips every time a screen comes up might make for a worse
viewer experience than leaving them on.
First iteration discussed in #484

Add integration for SlayTheRelics Twitch extension

---

src/main/java/stsjorbsmod/patches/SelfExertPatch.java

- adds check on existence of MasterDeckEquivalent before setting its ExertedField to true

Bugfix #486 CTD when Exerting card not in MasterDeck

---

src/main/java/stsjorbsmod/patches/CardUpgradeGlowCheckPatch.java

This is my first PR for JorbsMod but I've read the contribution guide and am attempting to follow it. 
Issue: Upgrading a card outside of combat can crash the game (rarely)
Crash log: https://pastebin.com/pEgtsWyP
Key lines from the log (at the very end):
```
java.lang.NullPointerException: null
at com.megacrit.cardcrawl.cards.AbstractCard.cardPlayable(AbstractCard.java:1010) ~[?:?]
at com.megacrit.cardcrawl.cards.AbstractCard.canUse(AbstractCard.java:1104) ~[?:?]
at com.megacrit.cardcrawl.cards.CardGroup.glowCheck(CardGroup.java:440) ~[?:?]
at stsjorbsmod.patches.CardUpgradeGlowCheckPatch$AbstractCard_upgradeName.patch(CardUpgradeGlowCheckPatch.java:20) ~[JorbsMod.jar:?]
```
`CardUpgradeGlowCheckPatch` seems to trigger a rare crash when upgrading a card outside of combat. From looking at …

Only check card glow in combat to avoid crash when upgrading cards outside of combat

---

src/main/java/stsjorbsmod/twitch/SlayTheRelicsIntegration.java

Follow-up to #485 now that the official docs for the exporter mod are
live, as linked from the Steam workshop page:
<https://steamcommunity.com/sharedfiles/filedetails/?id=1989770578>
wchargin-branch: slay-the-relics-docs-link

Add link to API docs for Slay the Relics

---

src/main/java/stsjorbsmod/powers/MirroredTechniquePower.java

fixes #562 
changed `ReflectionUtils.getPrivateField(m, AbstractMonster.class, "isMultiDmg")` to use .equals(true) to force getPrivateField to boolean, to get around a compilation error with openJDK

ReflectionUtils OpenJDK fix

---

src/main/java/stsjorbsmod/patches/ManifestPatch.java

- The chest rooms after the boss are the same y so the formula evaluates to -1 preventing increment without this if
- Every act except act 3 puts you at y=-1 before the first room, but act 3 is y=15 resulting in a reset of floor count without the if
- The Ending has an issue where boss rooms are always y=15 so it goes from y=2 to y=15 unless you stop the formula from running

Fixing Corner cases with floorCount

---

CHANGELOG.md
src/main/java/stsjorbsmod/cards/cull/FocusedRage.java
src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Card-Strings.json

> focused rage rework somehow (per card exerted this act?) - have it exert first so that it always gives at least a bit of strength
2(3) strength gained for playing itself.

Focused Rage includes itself in strength gain calculations.
