src/main/java/stsjorbsmod/actions/GainBlockPerPoisonAction.java
=> Fix crash when calculating block from poison-less enemy

src/main/java/stsjorbsmod/memories/WrathMemory.java
=> Fix wrath crash

src/main/java/stsjorbsmod/JorbsMod.java, src/main/java/stsjorbsmod/characters/Wanderer.java, src/main/java/stsjorbsmod/powers/MagicMirrorPower.java
I wanted to play the mod on the beta branch (and take my chances with any runtime inconsistencies). There were a few super trivial things to make it at least compile.
This is just a start obviously. I'll do some beta against on the beta branch to see if I can find any other issues. 
~ thefunkiestchicken
=> Fix v1.0/v2.0 incompatibilities

src/main/java/stsjorbsmod/memories/GluttonyMemory.java, src/main/java/stsjorbsmod/memories/GreedMemory.java, src/main/java/stsjorbsmod/memories/WrathMemory.java, src/main/java/stsjorbsmod/patches/EntombedPatch.java
Added checks against the monsters' halfDead property.
=> On monster death should not trigger on half kills

src/main/java/stsjorbsmod/actions/ChainLightningAction.java, src/main/java/stsjorbsmod/cards/wanderer/ChainLightning.java
This adds a visual and audio effect for each enemy hit by Chain Lightning. Resolves #76.
=> Adding Effects to Chain Lightning

src/main/java/stsjorbsmod/JorbsMod.java, src/main/java/stsjorbsmod/potions/BurningPotion.java, src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Potion-Strings.json
new burning potion
throwable, apply 8 burning
=> burning potion

src/main/java/stsjorbsmod/cards/wanderer/ChainLightning.java
I was thinking about this code, and thought it could be streamlined just a little bit. If this isn't the preferred style or is drastically less performant for some reason (my measurements were 0-1ms for the loop before the changes and after), I don't mind if we just toss this. Just thought I'd put it out there as a little simplification.
=> Minor refactoring around Chain Lightning's use.

src/main/java/stsjorbsmod/patches/OnModifyGoldPatch.java
Fix by only notifying all the things while in combat phase.
addresses #141
=> fix by making the notify a combat phase only thing.

src/main/java/stsjorbsmod/actions/DiscoveryAtCostAction.java, src/main/java/stsjorbsmod/cards/wanderer/ForbiddenGrimoire.java
Reimplementing the DiscoveryAction seemed less messy than patching.
=> Fix #153 so components have normal cost

src/main/java/stsjorbsmod/cards/wanderer/Inferno.java
Maybe instead of this, somehow a way to quickly check main branch jar compatibility?
=> fix specific instance of crash

src/main/java/stsjorbsmod/actions/ArcaneWeaponAction.java, src/main/java/stsjorbsmod/effects/ArcaneWeaponEffect.java, src/main/java/stsjorbsmod/powers/ArcaneWeaponPower.java
It would be good to use a more thematic color (and maybe even a different weapon shape). Currently, just using one of the crossed swords for the "Battle Start" banner. I'm not sure exactly how the color overrides the default green though.
addresses #56 
https://youtu.be/tOYSFkgaDns
=> Arcane weapon has a custom effect

src/main/resources/stsjorbsmodResources/localization/fra/JorbsMod-Card-Strings.json, src/main/resources/stsjorbsmodResources/localization/fra/JorbsMod-Character-Strings.json, src/main/resources/stsjorbsmodResources/localization/fra/JorbsMod-Event-Strings.json, src/main/resources/stsjorbsmodResources/localization/fra/JorbsMod-Keyword-Strings.json, src/main/resources/stsjorbsmodResources/localization/fra/JorbsMod-Potion-Strings.json, src/main/resources/stsjorbsmodResources/localization/fra/JorbsMod-Power-Strings.json, src/main/resources/stsjorbsmodResources/localization/fra/JorbsMod-Relic-Strings.json, src/main/resources/stsjorbsmodResources/localization/fra/JorbsMod-UI-Strings.json
a french localization so french jorbsers can jorbs
=> french localization so french jorbsers can play jorbs

src/main/java/stsjorbsmod/powers/BurningPower.java
apparently the attempt to copy only the gold was unsuccessful.
=> make burning render less similar to damage taken on the hp bar

src/main/java/stsjorbsmod/patches/NlothsGiftPatch.java
1. Fragile Mind can't be offered to N'loth. Tested by entering the event with any other relics (total 3) multiple times using `event N'loth`.
2. N'loth event can't occur if there are only two relics, Fragile Mind and any other. Unsure how to test.
=> Fragile mind nloths gift

src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Card-Strings.json, src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Keyword-Strings.json
=> legendary keyword for forbidden grimoire

src/main/java/stsjorbsmod/cards/CustomJorbsModCard.java, src/main/java/stsjorbsmod/cards/wanderer/AnimateObjects.java, src/main/java/stsjorbsmod/cards/wanderer/MagicMissiles.java, src/main/java/stsjorbsmod/cards/wanderer/Mania.java, src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Card-Strings.json
Add dynamic card descriptions to Animate Objects, Mania, and Magic Missiles.
=> Dynamic card text update

src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Card-Strings.json
=> add description

src/main/java/stsjorbsmod/cards/cull/WastingEssence.java, src/main/java/stsjorbsmod/powers/WastingEssencePower.java
- moved curse creation from WastingEssencePower method onInitialApplication to Wasting Essence use method
=> Bugfix #281: Additional Wasting Essence do not add curses when played

src/main/java/stsjorbsmod/patches/RenderBurningBlockPatch.java
If there's block to show and the creature is burning, show fire icon behind the block icon
addresses #243
=> Adds a fire icon behind the block icon

src/main/java/stsjorbsmod/cards/cull/Frostbite.java, src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Keyword-Strings.json
- changes rarity on upgrade to Rare, so that consuming it gives a better reward. Turns it from a garbage upgrade to actually worth considering.
=> Made a better Frostbite upgrade

src/main/java/stsjorbsmod/cards/wanderer/OldPocket.java
=> Old Pocket shouldn't show up with Nilry's Codex anymore

src/main/java/stsjorbsmod/cards/cull/Abjure.java, src/main/java/stsjorbsmod/cards/cull/Miracle_Cull.java, src/main/java/stsjorbsmod/cards/cull/WakingDream.java, src/main/java/stsjorbsmod/cards/wanderer/MageArmor.java, src/main/java/stsjorbsmod/cards/wanderer/materialcomponents/Chamomile.java, src/main/java/stsjorbsmod/cards/wanderer/materialcomponents/Moss.java, src/main/java/stsjorbsmod/cards/wanderer/materialcomponents/SnakeOil.java, src/main/java/stsjorbsmod/cards/wanderer/materialcomponents/Stone.java, src/main/java/stsjorbsmod/cards/wanderer/materialcomponents/Web.java
=> refactor multiple cards to use AbstractCard#selfRetain

src/main/java/stsjorbsmod/patches/BurningPatch.java
Moves the damage counter reset to before burning damage.
Verified that it doesn't reset twice (before burning and when atStartOfTurn is normally called)
=> move InvinciblePower's amount reset to before burning damage

src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Card-Strings.json, src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Power-Strings.json
rewording pendant as suggested
"reduce the first damage taken each turn by 1"
=> reword Strange Pendant

src/main/java/stsjorbsmod/cards/wanderer/PurgeMind.java, src/main/java/stsjorbsmod/cards/wanderer/Trauma.java, src/main/java/stsjorbsmod/memories/LustMemory.java, src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Keyword-Strings.json, src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Memory-Strings.json
Purge mind upgrade 11 -> 9.
Trauma damage 32 -> 28.
Trauma+ damage 37 -> 33
Lust no longer applies burning on remember.
=> balance 20200205

src/main/java/stsjorbsmod/actions/MakeMaterialComponentsInHandAction.java, src/main/java/stsjorbsmod/cards/wanderer/BookOfTongues.java, src/main/java/stsjorbsmod/cards/wanderer/FranticSearch.java, src/main/java/stsjorbsmod/powers/BookOfTonguesUpgradedPower.java, src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Card-Strings.json, src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Power-Strings.json
=> new upgraded version of Book of Tongues power

src/main/java/stsjorbsmod/powers/FlameWardPower.java
=> using flame barrier effect again when attacked

src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Card-Strings.json
=> Book of Tongues upgrade typo

src/main/java/stsjorbsmod/potions/BurningPotion.java, src/main/java/stsjorbsmod/potions/DimensionDoorPotion.java, src/main/java/stsjorbsmod/potions/GhostPoisonPotion.java, src/main/java/stsjorbsmod/potions/LiquidClarity.java, src/main/java/stsjorbsmod/potions/LiquidVirtue.java, src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Potion-Strings.json
=> move potency, description, and tips to initializeData

src/main/java/stsjorbsmod/cards/wanderer/materialcomponents/MaterialComponentsDeck.java
I fully admit that it's kind of sloppy, and leaves something to be desired, but I'm 99% sure that for our use cases, we'll always draw unique material components.
addresses #343
=> unique material components when drawing a few

src/main/java/stsjorbsmod/actions/ArcaneWeaponAction.java, src/main/java/stsjorbsmod/util/CombatUtils.java
=> arcane weapon cannot target banished monsters anymore

src/main/java/stsjorbsmod/characters/Wanderer.java, src/main/java/stsjorbsmod/memories/SnapCounter.java
addresses #351 
Flames center around book always. Flames rotate clockwise facing right, counterclockwise facing left
=> counter follows the player

src/main/java/stsjorbsmod/cards/wanderer/materialcomponents/Brambles.java, src/main/java/stsjorbsmod/cards/wanderer/materialcomponents/Chamomile.java, src/main/java/stsjorbsmod/cards/wanderer/materialcomponents/EnergyBulb.java, src/main/java/stsjorbsmod/cards/wanderer/materialcomponents/Eye.java, src/main/java/stsjorbsmod/cards/wanderer/materialcomponents/LooseLeaf.java, src/main/java/stsjorbsmod/cards/wanderer/materialcomponents/MaterialComponent.java, src/main/java/stsjorbsmod/cards/wanderer/materialcomponents/MaterialComponentsDeck.java, src/main/java/stsjorbsmod/cards/wanderer/materialcomponents/Moss.java, src/main/java/stsjorbsmod/cards/wanderer/materialcomponents/OakLeaf.java, src/main/java/stsjorbsmod/cards/wanderer/materialcomponents/Quicksilver.java, src/main/java/stsjorbsmod/cards/wanderer/materialcomponents/Rot.java, src/main/java/stsjorbsmod/cards/wanderer/materialcomponents/SnakeOil.java, src/main/java/stsjorbsmod/cards/wanderer/materialcomponents/Steel.java, src/main/java/stsjorbsmod/cards/wanderer/materialcomponents/Stone.java, src/main/java/stsjorbsmod/cards/wanderer/materialcomponents/StrangePendant.java, src/main/java/stsjorbsmod/cards/wanderer/materialcomponents/Sulfur.java, src/main/java/stsjorbsmod/cards/wanderer/materialcomponents/TimeEddy.java, src/main/java/stsjorbsmod/cards/wanderer/materialcomponents/Web.java, src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Card-Strings.json
=> Brambles damage increases with material components played

src/main/java/stsjorbsmod/cards/wanderer/ForbiddenGrimoire.java, src/main/java/stsjorbsmod/cards/wanderer/Prepare.java, src/main/java/stsjorbsmod/powers/FindFamiliarPower.java, src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Card-Strings.json, src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Power-Strings.json
- Grimoire returns every 4 cards after playing
- Prepare gains block before gaining coil
- Find Familiar is a start of turn power
=> Balance pass 20200211

src/main/java/stsjorbsmod/powers/FearPower.java
addresses #385 
This should work if a fight exists with multiple monsters on either side of the player. That is not tested though. Works in the 4 scenarios of Shield and Spear fight though.
=> if the spear is no longer here because of fear, face its dear

src/main/java/stsjorbsmod/patches/BanishPatch.java
=> Banish interactions

README.md
Thank you for this fantastic mod!
=> Fix missing link in readme

src/main/java/stsjorbsmod/actions/PermanentlyModifyDamageAction.java
Fixes #432 
I wasn't really able to figure out the exact scenario, but this seemed to be a good incremental change.
=> applyPower when PermanentlyModifyDamageAction activates

src/main/resources/stsjorbsmodResources/localization/zhs/JorbsMod-Card-Strings.json, src/main/resources/stsjorbsmodResources/localization/zhs/JorbsMod-Keyword-Strings.json, src/main/resources/stsjorbsmodResources/localization/zhs/JorbsMod-Power-Strings.json, src/main/resources/stsjorbsmodResources/localization/zhs/JorbsMod-Relic-Strings.json, src/main/resources/stsjorbsmodResources/localization/zhs/JorbsMod-UI-Strings.json
ZHS translation for upcoming cards, keywords, powers, relics and UI contents.
And an overall check is made to keep everything up to date.
=> Update zhs translation

src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Card-Strings.json
Fixed card, was missing exert.
=> Added "Exert" keyword to Assertion, was missing

src/main/java/stsjorbsmod/cards/cull/CoupDeGrace.java
=> making coup de grace rare

CHANGELOG.md, src/main/java/stsjorbsmod/cards/cull/SpiritShield_Cull.java, src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Card-Strings.json, src/main/resources/stsjorbsmodResources/localization/spa/JorbsMod-Card-Strings.json
rebalancing CULLs spirit shield, addresses #571
=> rebalancing CULLs spirit shield, addresses #571

CHANGELOG.md, src/main/java/stsjorbsmod/cards/cull/deckoftrials/Blasphemer.java, src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Card-Strings.json, src/main/resources/stsjorbsmodResources/localization/spa/JorbsMod-Card-Strings.json
=> blasphemer rebalance, fixes #572

src/main/resources/stsjorbsmodResources/localization/zhs/JorbsMod-Card-Strings.json, src/main/resources/stsjorbsmodResources/localization/zhs/JorbsMod-Keyword-Strings.json, src/main/resources/stsjorbsmodResources/localization/zhs/JorbsMod-Power-Strings.json, src/main/resources/stsjorbsmodResources/localization/zhs/JorbsMod-Relic-Strings.json
=> zhs localizations updated

CHANGELOG.md, src/main/java/stsjorbsmod/cards/cull/Taunt.java, src/main/resources/stsjorbsmodResources/localization/eng/JorbsMod-Card-Strings.json, src/main/resources/stsjorbsmodResources/localization/spa/JorbsMod-Card-Strings.json, src/main/resources/stsjorbsmodResources/localization/zhs/JorbsMod-Card-Strings.json
Simple bugfix for taunt upgrade
=> Bugfix for Taunt Upgrade
